name: doctor_plus
description: "Doctor Plus"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  http:
  intl:
  crypto:
  googleapis:
  file_picker:
  image_picker:
  flutter_bloc:
  fluttertoast: ^8.2.6
  firebase_core:
  firebase_auth:
  awesome_dialog:
  google_sign_in:
  toastification:
  cupertino_icons:
  cloud_firestore:
  firebase_storage:
  shared_preferences:
  font_awesome_flutter:
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
