name: doctor_plus
description: "Doctor Plus"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  dio: ^5.4.3+1
  intl: ^0.19.0
  crypto: ^3.0.3
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  file_picker: ^8.0.5
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  awesome_dialog: ^3.2.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.0.1
  carousel_slider: ^4.2.1
  firebase_storage: ^12.0.1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.3
  contained_tab_bar_view: ^0.8.0
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.3
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^2.0.12

  # googleapis: ^13.2.0
  google_sign_in: ^6.2.1
  # toastification: ^2.0.0
  # font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/icons/
    - assets/imgs/
    - assets/specializations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
